# ubicación: backend/appointments-service/dockerfile

FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY pom.xml ./pom.xml
COPY appointments-service/pom.xml ./appointments-service/pom.xml
RUN mvn -f appointments-service/pom.xml -B dependency:go-offline

COPY appointments-service/src ./appointments-service/src
RUN mvn -f appointments-service/pom.xml -B clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /workspace/appointments-service/target/*.jar app.jar

EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
