spring.application.name=appointments-service
server.port=8082

# Postgres datasource (added by Copilot)
spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:55955/railway
spring.datasource.username=postgres
spring.datasource.password=BCCHoyFdVhoawXRVxnJhPkKRuSIdroIt
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Hikari pool tuning
spring.datasource.hikari.maximum-pool-size=10
