spring.application.name=appointments-service
server.port=8082

# Postgres datasource
spring.datasource.url=jdbc:postgresql://db:5432/agendafacil
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Hikari pool tuning
spring.datasource.hikari.maximum-pool-size=10

# desactivado porque no hay discovery-server corriendo en docker-compose todavía.
# si se agrega discovery-server más adelante, borrar esta línea.
eureka.client.enabled=false
