# ubicación: backend/notifications-service/dockerfile

FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY pom.xml ./pom.xml
COPY notifications-service/pom.xml ./notifications-service/pom.xml
RUN mvn -f notifications-service/pom.xml -B dependency:go-offline

COPY notifications-service/src ./notifications-service/src
RUN mvn -f notifications-service/pom.xml -B clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /workspace/notifications-service/target/*.jar app.jar

EXPOSE 8085
ENTRYPOINT ["java", "-jar", "app.jar"]
