# ubicación: backend/services-service/dockerfile

FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY pom.xml ./pom.xml
COPY services-service/pom.xml ./services-service/pom.xml
RUN mvn -f services-service/pom.xml -B dependency:go-offline

COPY services-service/src ./services-service/src
RUN mvn -f services-service/pom.xml -B clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /workspace/services-service/target/*.jar app.jar

EXPOSE 8084
ENTRYPOINT ["java", "-jar", "app.jar"]
