# ubicación: backend/clients-service/dockerfile

FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY pom.xml ./pom.xml
COPY clients-service/pom.xml ./clients-service/pom.xml
RUN mvn -f clients-service/pom.xml -B dependency:go-offline

COPY clients-service/src ./clients-service/src
RUN mvn -f clients-service/pom.xml -B clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /workspace/clients-service/target/*.jar app.jar

EXPOSE 8083
ENTRYPOINT ["java", "-jar", "app.jar"]
